# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Building Security
email: hello@purefan.me
description: > # this means to ignore newlines until "baseurl:"
  Articles about security, secure coding, data governance and
  other information security topics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://purefan.dev" # the base hostname & protocol for your site
twitter_username: purefan
github_username:  purefan
permalink: /:title.html

# Build settings
markdown: kramdown
